### ISSUE TITLE
Definição do Schema PIX tem Objeto "pagador" ?

### ISSUE THREAD

**Issue by dopidaniel** [bacen/pix-api#495]
Na especificação 2.6.2, a definição de Schema do Objeto **Pix**, cita como Propriedade obrigatória, o objeto "pagador"
https://app.swaggerhub.com/apis/Projeto-ACBr/api-pix/2.6.2#/Pix

```
    Pix:
      type: object
      title: Pix
      required:
        - endToEndId
        - valor
        - horario
        - pagador       <---- aqui ------
```

Porém o objeto "pagador" não está definido em "properties" desse Schema...

O objeto "pagador" realmente é uma propriedade do objeto "Pix" ?
